// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_QUERY_QUERYARCHIVE_H_
#define FLATBUFFERS_GENERATED_QUERY_QUERYARCHIVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace QueryArchive {

struct Message;
struct MessageBuilder;

struct MessagePair;
struct MessagePairBuilder;

struct SessionMeta;
struct SessionMetaBuilder;

struct Session;
struct SessionBuilder;

struct SearchHit;
struct SearchHitBuilder;

struct SearchResponse;
struct SearchResponseBuilder;

struct InitResponse;
struct InitResponseBuilder;

struct RootResponse;
struct RootResponseBuilder;

struct InitRequest;
struct InitRequestBuilder;

struct SearchRequest;
struct SearchRequestBuilder;

struct RootRequest;
struct RootRequestBuilder;

enum Role : int8_t {
  Role_User = 0,
  Role_AI = 1,
  Role_System = 2,
  Role_MIN = Role_User,
  Role_MAX = Role_System
};

inline const Role (&EnumValuesRole())[3] {
  static const Role values[] = {
    Role_User,
    Role_AI,
    Role_System
  };
  return values;
}

inline const char * const *EnumNamesRole() {
  static const char * const names[4] = {
    "User",
    "AI",
    "System",
    nullptr
  };
  return names;
}

inline const char *EnumNameRole(Role e) {
  if (flatbuffers::IsOutRange(e, Role_User, Role_System)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRole()[index];
}

enum AnyResponse : uint8_t {
  AnyResponse_NONE = 0,
  AnyResponse_InitResponse = 1,
  AnyResponse_SearchResponse = 2,
  AnyResponse_MIN = AnyResponse_NONE,
  AnyResponse_MAX = AnyResponse_SearchResponse
};

inline const AnyResponse (&EnumValuesAnyResponse())[3] {
  static const AnyResponse values[] = {
    AnyResponse_NONE,
    AnyResponse_InitResponse,
    AnyResponse_SearchResponse
  };
  return values;
}

inline const char * const *EnumNamesAnyResponse() {
  static const char * const names[4] = {
    "NONE",
    "InitResponse",
    "SearchResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNameAnyResponse(AnyResponse e) {
  if (flatbuffers::IsOutRange(e, AnyResponse_NONE, AnyResponse_SearchResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAnyResponse()[index];
}

template<typename T> struct AnyResponseTraits {
  static const AnyResponse enum_value = AnyResponse_NONE;
};

template<> struct AnyResponseTraits<QueryArchive::InitResponse> {
  static const AnyResponse enum_value = AnyResponse_InitResponse;
};

template<> struct AnyResponseTraits<QueryArchive::SearchResponse> {
  static const AnyResponse enum_value = AnyResponse_SearchResponse;
};

bool VerifyAnyResponse(flatbuffers::Verifier &verifier, const void *obj, AnyResponse type);
bool VerifyAnyResponseVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

enum AnyRequest : uint8_t {
  AnyRequest_NONE = 0,
  AnyRequest_InitRequest = 1,
  AnyRequest_SearchRequest = 2,
  AnyRequest_MIN = AnyRequest_NONE,
  AnyRequest_MAX = AnyRequest_SearchRequest
};

inline const AnyRequest (&EnumValuesAnyRequest())[3] {
  static const AnyRequest values[] = {
    AnyRequest_NONE,
    AnyRequest_InitRequest,
    AnyRequest_SearchRequest
  };
  return values;
}

inline const char * const *EnumNamesAnyRequest() {
  static const char * const names[4] = {
    "NONE",
    "InitRequest",
    "SearchRequest",
    nullptr
  };
  return names;
}

inline const char *EnumNameAnyRequest(AnyRequest e) {
  if (flatbuffers::IsOutRange(e, AnyRequest_NONE, AnyRequest_SearchRequest)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAnyRequest()[index];
}

template<typename T> struct AnyRequestTraits {
  static const AnyRequest enum_value = AnyRequest_NONE;
};

template<> struct AnyRequestTraits<QueryArchive::InitRequest> {
  static const AnyRequest enum_value = AnyRequest_InitRequest;
};

template<> struct AnyRequestTraits<QueryArchive::SearchRequest> {
  static const AnyRequest enum_value = AnyRequest_SearchRequest;
};

bool VerifyAnyRequest(flatbuffers::Verifier &verifier, const void *obj, AnyRequest type);
bool VerifyAnyRequestVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROLE = 4,
    VT_CONTENT = 6
  };
  QueryArchive::Role role() const {
    return static_cast<QueryArchive::Role>(GetField<int8_t>(VT_ROLE, 0));
  }
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_ROLE, 1) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           verifier.EndTable();
  }
};

struct MessageBuilder {
  typedef Message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_role(QueryArchive::Role role) {
    fbb_.AddElement<int8_t>(Message::VT_ROLE, static_cast<int8_t>(role), 0);
  }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(Message::VT_CONTENT, content);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    QueryArchive::Role role = QueryArchive::Role_User,
    flatbuffers::Offset<flatbuffers::String> content = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_role(role);
  return builder_.Finish();
}

inline flatbuffers::Offset<Message> CreateMessageDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    QueryArchive::Role role = QueryArchive::Role_User,
    const char *content = nullptr) {
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return QueryArchive::CreateMessage(
      _fbb,
      role,
      content__);
}

struct MessagePair FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessagePairBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAIR_INDEX = 4,
    VT_USER_MSG = 6,
    VT_AI_MSG = 8
  };
  int32_t pair_index() const {
    return GetField<int32_t>(VT_PAIR_INDEX, 0);
  }
  const QueryArchive::Message *user_msg() const {
    return GetPointer<const QueryArchive::Message *>(VT_USER_MSG);
  }
  const QueryArchive::Message *ai_msg() const {
    return GetPointer<const QueryArchive::Message *>(VT_AI_MSG);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PAIR_INDEX, 4) &&
           VerifyOffset(verifier, VT_USER_MSG) &&
           verifier.VerifyTable(user_msg()) &&
           VerifyOffset(verifier, VT_AI_MSG) &&
           verifier.VerifyTable(ai_msg()) &&
           verifier.EndTable();
  }
};

struct MessagePairBuilder {
  typedef MessagePair Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pair_index(int32_t pair_index) {
    fbb_.AddElement<int32_t>(MessagePair::VT_PAIR_INDEX, pair_index, 0);
  }
  void add_user_msg(flatbuffers::Offset<QueryArchive::Message> user_msg) {
    fbb_.AddOffset(MessagePair::VT_USER_MSG, user_msg);
  }
  void add_ai_msg(flatbuffers::Offset<QueryArchive::Message> ai_msg) {
    fbb_.AddOffset(MessagePair::VT_AI_MSG, ai_msg);
  }
  explicit MessagePairBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MessagePair> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MessagePair>(end);
    return o;
  }
};

inline flatbuffers::Offset<MessagePair> CreateMessagePair(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t pair_index = 0,
    flatbuffers::Offset<QueryArchive::Message> user_msg = 0,
    flatbuffers::Offset<QueryArchive::Message> ai_msg = 0) {
  MessagePairBuilder builder_(_fbb);
  builder_.add_ai_msg(ai_msg);
  builder_.add_user_msg(user_msg);
  builder_.add_pair_index(pair_index);
  return builder_.Finish();
}

struct SessionMeta FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SessionMetaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSION_ID = 4,
    VT_TITLE = 6,
    VT_MODEL = 8,
    VT_TIMESTAMP = 10
  };
  const flatbuffers::String *session_id() const {
    return GetPointer<const flatbuffers::String *>(VT_SESSION_ID);
  }
  const flatbuffers::String *title() const {
    return GetPointer<const flatbuffers::String *>(VT_TITLE);
  }
  const flatbuffers::String *model() const {
    return GetPointer<const flatbuffers::String *>(VT_MODEL);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SESSION_ID) &&
           verifier.VerifyString(session_id()) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyOffset(verifier, VT_MODEL) &&
           verifier.VerifyString(model()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           verifier.EndTable();
  }
};

struct SessionMetaBuilder {
  typedef SessionMeta Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session_id(flatbuffers::Offset<flatbuffers::String> session_id) {
    fbb_.AddOffset(SessionMeta::VT_SESSION_ID, session_id);
  }
  void add_title(flatbuffers::Offset<flatbuffers::String> title) {
    fbb_.AddOffset(SessionMeta::VT_TITLE, title);
  }
  void add_model(flatbuffers::Offset<flatbuffers::String> model) {
    fbb_.AddOffset(SessionMeta::VT_MODEL, model);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(SessionMeta::VT_TIMESTAMP, timestamp, 0);
  }
  explicit SessionMetaBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SessionMeta> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SessionMeta>(end);
    return o;
  }
};

inline flatbuffers::Offset<SessionMeta> CreateSessionMeta(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> session_id = 0,
    flatbuffers::Offset<flatbuffers::String> title = 0,
    flatbuffers::Offset<flatbuffers::String> model = 0,
    uint64_t timestamp = 0) {
  SessionMetaBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_model(model);
  builder_.add_title(title);
  builder_.add_session_id(session_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<SessionMeta> CreateSessionMetaDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *session_id = nullptr,
    const char *title = nullptr,
    const char *model = nullptr,
    uint64_t timestamp = 0) {
  auto session_id__ = session_id ? _fbb.CreateString(session_id) : 0;
  auto title__ = title ? _fbb.CreateString(title) : 0;
  auto model__ = model ? _fbb.CreateString(model) : 0;
  return QueryArchive::CreateSessionMeta(
      _fbb,
      session_id__,
      title__,
      model__,
      timestamp);
}

struct Session FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SessionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_META_DATA = 4,
    VT_PAIRS = 6
  };
  const QueryArchive::SessionMeta *meta_data() const {
    return GetPointer<const QueryArchive::SessionMeta *>(VT_META_DATA);
  }
  const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::MessagePair>> *pairs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::MessagePair>> *>(VT_PAIRS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_META_DATA) &&
           verifier.VerifyTable(meta_data()) &&
           VerifyOffset(verifier, VT_PAIRS) &&
           verifier.VerifyVector(pairs()) &&
           verifier.VerifyVectorOfTables(pairs()) &&
           verifier.EndTable();
  }
};

struct SessionBuilder {
  typedef Session Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_meta_data(flatbuffers::Offset<QueryArchive::SessionMeta> meta_data) {
    fbb_.AddOffset(Session::VT_META_DATA, meta_data);
  }
  void add_pairs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::MessagePair>>> pairs) {
    fbb_.AddOffset(Session::VT_PAIRS, pairs);
  }
  explicit SessionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Session> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Session>(end);
    return o;
  }
};

inline flatbuffers::Offset<Session> CreateSession(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<QueryArchive::SessionMeta> meta_data = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::MessagePair>>> pairs = 0) {
  SessionBuilder builder_(_fbb);
  builder_.add_pairs(pairs);
  builder_.add_meta_data(meta_data);
  return builder_.Finish();
}

inline flatbuffers::Offset<Session> CreateSessionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<QueryArchive::SessionMeta> meta_data = 0,
    const std::vector<flatbuffers::Offset<QueryArchive::MessagePair>> *pairs = nullptr) {
  auto pairs__ = pairs ? _fbb.CreateVector<flatbuffers::Offset<QueryArchive::MessagePair>>(*pairs) : 0;
  return QueryArchive::CreateSession(
      _fbb,
      meta_data,
      pairs__);
}

struct SearchHit FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SearchHitBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSION_ID = 4,
    VT_MATCHED_PAIR_INDICES = 6
  };
  const flatbuffers::String *session_id() const {
    return GetPointer<const flatbuffers::String *>(VT_SESSION_ID);
  }
  const flatbuffers::Vector<int32_t> *matched_pair_indices() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_MATCHED_PAIR_INDICES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SESSION_ID) &&
           verifier.VerifyString(session_id()) &&
           VerifyOffset(verifier, VT_MATCHED_PAIR_INDICES) &&
           verifier.VerifyVector(matched_pair_indices()) &&
           verifier.EndTable();
  }
};

struct SearchHitBuilder {
  typedef SearchHit Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session_id(flatbuffers::Offset<flatbuffers::String> session_id) {
    fbb_.AddOffset(SearchHit::VT_SESSION_ID, session_id);
  }
  void add_matched_pair_indices(flatbuffers::Offset<flatbuffers::Vector<int32_t>> matched_pair_indices) {
    fbb_.AddOffset(SearchHit::VT_MATCHED_PAIR_INDICES, matched_pair_indices);
  }
  explicit SearchHitBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SearchHit> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SearchHit>(end);
    return o;
  }
};

inline flatbuffers::Offset<SearchHit> CreateSearchHit(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> session_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> matched_pair_indices = 0) {
  SearchHitBuilder builder_(_fbb);
  builder_.add_matched_pair_indices(matched_pair_indices);
  builder_.add_session_id(session_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<SearchHit> CreateSearchHitDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *session_id = nullptr,
    const std::vector<int32_t> *matched_pair_indices = nullptr) {
  auto session_id__ = session_id ? _fbb.CreateString(session_id) : 0;
  auto matched_pair_indices__ = matched_pair_indices ? _fbb.CreateVector<int32_t>(*matched_pair_indices) : 0;
  return QueryArchive::CreateSearchHit(
      _fbb,
      session_id__,
      matched_pair_indices__);
}

struct SearchResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SearchResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HITS = 4,
    VT_SESSIONS = 6,
    VT_TOOK_MS = 8
  };
  const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::SearchHit>> *hits() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::SearchHit>> *>(VT_HITS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>> *sessions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>> *>(VT_SESSIONS);
  }
  int32_t took_ms() const {
    return GetField<int32_t>(VT_TOOK_MS, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HITS) &&
           verifier.VerifyVector(hits()) &&
           verifier.VerifyVectorOfTables(hits()) &&
           VerifyOffset(verifier, VT_SESSIONS) &&
           verifier.VerifyVector(sessions()) &&
           verifier.VerifyVectorOfTables(sessions()) &&
           VerifyField<int32_t>(verifier, VT_TOOK_MS, 4) &&
           verifier.EndTable();
  }
};

struct SearchResponseBuilder {
  typedef SearchResponse Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_hits(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::SearchHit>>> hits) {
    fbb_.AddOffset(SearchResponse::VT_HITS, hits);
  }
  void add_sessions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>>> sessions) {
    fbb_.AddOffset(SearchResponse::VT_SESSIONS, sessions);
  }
  void add_took_ms(int32_t took_ms) {
    fbb_.AddElement<int32_t>(SearchResponse::VT_TOOK_MS, took_ms, 0);
  }
  explicit SearchResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SearchResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SearchResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<SearchResponse> CreateSearchResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::SearchHit>>> hits = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>>> sessions = 0,
    int32_t took_ms = 0) {
  SearchResponseBuilder builder_(_fbb);
  builder_.add_took_ms(took_ms);
  builder_.add_sessions(sessions);
  builder_.add_hits(hits);
  return builder_.Finish();
}

inline flatbuffers::Offset<SearchResponse> CreateSearchResponseDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<QueryArchive::SearchHit>> *hits = nullptr,
    const std::vector<flatbuffers::Offset<QueryArchive::Session>> *sessions = nullptr,
    int32_t took_ms = 0) {
  auto hits__ = hits ? _fbb.CreateVector<flatbuffers::Offset<QueryArchive::SearchHit>>(*hits) : 0;
  auto sessions__ = sessions ? _fbb.CreateVector<flatbuffers::Offset<QueryArchive::Session>>(*sessions) : 0;
  return QueryArchive::CreateSearchResponse(
      _fbb,
      hits__,
      sessions__,
      took_ms);
}

struct InitResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InitResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSIONS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>> *sessions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>> *>(VT_SESSIONS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SESSIONS) &&
           verifier.VerifyVector(sessions()) &&
           verifier.VerifyVectorOfTables(sessions()) &&
           verifier.EndTable();
  }
};

struct InitResponseBuilder {
  typedef InitResponse Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_sessions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>>> sessions) {
    fbb_.AddOffset(InitResponse::VT_SESSIONS, sessions);
  }
  explicit InitResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<InitResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<InitResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<InitResponse> CreateInitResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<QueryArchive::Session>>> sessions = 0) {
  InitResponseBuilder builder_(_fbb);
  builder_.add_sessions(sessions);
  return builder_.Finish();
}

inline flatbuffers::Offset<InitResponse> CreateInitResponseDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<QueryArchive::Session>> *sessions = nullptr) {
  auto sessions__ = sessions ? _fbb.CreateVector<flatbuffers::Offset<QueryArchive::Session>>(*sessions) : 0;
  return QueryArchive::CreateInitResponse(
      _fbb,
      sessions__);
}

struct RootResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RootResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  QueryArchive::AnyResponse payload_type() const {
    return static_cast<QueryArchive::AnyResponse>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const QueryArchive::InitResponse *payload_as_InitResponse() const {
    return payload_type() == QueryArchive::AnyResponse_InitResponse ? static_cast<const QueryArchive::InitResponse *>(payload()) : nullptr;
  }
  const QueryArchive::SearchResponse *payload_as_SearchResponse() const {
    return payload_type() == QueryArchive::AnyResponse_SearchResponse ? static_cast<const QueryArchive::SearchResponse *>(payload()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyAnyResponse(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const QueryArchive::InitResponse *RootResponse::payload_as<QueryArchive::InitResponse>() const {
  return payload_as_InitResponse();
}

template<> inline const QueryArchive::SearchResponse *RootResponse::payload_as<QueryArchive::SearchResponse>() const {
  return payload_as_SearchResponse();
}

struct RootResponseBuilder {
  typedef RootResponse Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_payload_type(QueryArchive::AnyResponse payload_type) {
    fbb_.AddElement<uint8_t>(RootResponse::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(RootResponse::VT_PAYLOAD, payload);
  }
  explicit RootResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RootResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RootResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<RootResponse> CreateRootResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    QueryArchive::AnyResponse payload_type = QueryArchive::AnyResponse_NONE,
    flatbuffers::Offset<void> payload = 0) {
  RootResponseBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct InitRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InitRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LIMIT = 4
  };
  int32_t limit() const {
    return GetField<int32_t>(VT_LIMIT, 30);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_LIMIT, 4) &&
           verifier.EndTable();
  }
};

struct InitRequestBuilder {
  typedef InitRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_limit(int32_t limit) {
    fbb_.AddElement<int32_t>(InitRequest::VT_LIMIT, limit, 30);
  }
  explicit InitRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<InitRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<InitRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<InitRequest> CreateInitRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t limit = 30) {
  InitRequestBuilder builder_(_fbb);
  builder_.add_limit(limit);
  return builder_.Finish();
}

struct SearchRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SearchRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEYWORD = 4,
    VT_LIMIT = 6
  };
  const flatbuffers::String *keyword() const {
    return GetPointer<const flatbuffers::String *>(VT_KEYWORD);
  }
  int32_t limit() const {
    return GetField<int32_t>(VT_LIMIT, 30);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEYWORD) &&
           verifier.VerifyString(keyword()) &&
           VerifyField<int32_t>(verifier, VT_LIMIT, 4) &&
           verifier.EndTable();
  }
};

struct SearchRequestBuilder {
  typedef SearchRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_keyword(flatbuffers::Offset<flatbuffers::String> keyword) {
    fbb_.AddOffset(SearchRequest::VT_KEYWORD, keyword);
  }
  void add_limit(int32_t limit) {
    fbb_.AddElement<int32_t>(SearchRequest::VT_LIMIT, limit, 30);
  }
  explicit SearchRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SearchRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SearchRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<SearchRequest> CreateSearchRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> keyword = 0,
    int32_t limit = 30) {
  SearchRequestBuilder builder_(_fbb);
  builder_.add_limit(limit);
  builder_.add_keyword(keyword);
  return builder_.Finish();
}

inline flatbuffers::Offset<SearchRequest> CreateSearchRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *keyword = nullptr,
    int32_t limit = 30) {
  auto keyword__ = keyword ? _fbb.CreateString(keyword) : 0;
  return QueryArchive::CreateSearchRequest(
      _fbb,
      keyword__,
      limit);
}

struct RootRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RootRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  QueryArchive::AnyRequest payload_type() const {
    return static_cast<QueryArchive::AnyRequest>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const QueryArchive::InitRequest *payload_as_InitRequest() const {
    return payload_type() == QueryArchive::AnyRequest_InitRequest ? static_cast<const QueryArchive::InitRequest *>(payload()) : nullptr;
  }
  const QueryArchive::SearchRequest *payload_as_SearchRequest() const {
    return payload_type() == QueryArchive::AnyRequest_SearchRequest ? static_cast<const QueryArchive::SearchRequest *>(payload()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyAnyRequest(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const QueryArchive::InitRequest *RootRequest::payload_as<QueryArchive::InitRequest>() const {
  return payload_as_InitRequest();
}

template<> inline const QueryArchive::SearchRequest *RootRequest::payload_as<QueryArchive::SearchRequest>() const {
  return payload_as_SearchRequest();
}

struct RootRequestBuilder {
  typedef RootRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_payload_type(QueryArchive::AnyRequest payload_type) {
    fbb_.AddElement<uint8_t>(RootRequest::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(RootRequest::VT_PAYLOAD, payload);
  }
  explicit RootRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RootRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RootRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<RootRequest> CreateRootRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    QueryArchive::AnyRequest payload_type = QueryArchive::AnyRequest_NONE,
    flatbuffers::Offset<void> payload = 0) {
  RootRequestBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyAnyResponse(flatbuffers::Verifier &verifier, const void *obj, AnyResponse type) {
  switch (type) {
    case AnyResponse_NONE: {
      return true;
    }
    case AnyResponse_InitResponse: {
      auto ptr = reinterpret_cast<const QueryArchive::InitResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyResponse_SearchResponse: {
      auto ptr = reinterpret_cast<const QueryArchive::SearchResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyAnyResponseVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAnyResponse(
        verifier,  values->Get(i), types->GetEnum<AnyResponse>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyAnyRequest(flatbuffers::Verifier &verifier, const void *obj, AnyRequest type) {
  switch (type) {
    case AnyRequest_NONE: {
      return true;
    }
    case AnyRequest_InitRequest: {
      auto ptr = reinterpret_cast<const QueryArchive::InitRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnyRequest_SearchRequest: {
      auto ptr = reinterpret_cast<const QueryArchive::SearchRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyAnyRequestVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAnyRequest(
        verifier,  values->Get(i), types->GetEnum<AnyRequest>(i))) {
      return false;
    }
  }
  return true;
}

inline const QueryArchive::RootResponse *GetRootResponse(const void *buf) {
  return flatbuffers::GetRoot<QueryArchive::RootResponse>(buf);
}

inline const QueryArchive::RootResponse *GetSizePrefixedRootResponse(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<QueryArchive::RootResponse>(buf);
}

inline bool VerifyRootResponseBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<QueryArchive::RootResponse>(nullptr);
}

inline bool VerifySizePrefixedRootResponseBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<QueryArchive::RootResponse>(nullptr);
}

inline void FinishRootResponseBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<QueryArchive::RootResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRootResponseBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<QueryArchive::RootResponse> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace QueryArchive

#endif  // FLATBUFFERS_GENERATED_QUERY_QUERYARCHIVE_H_
