// This file simulates the data structure that would be generated by FlatBuffers.
// In a real implementation, you would use the generated classes from `chat.fbs`.

export enum Role {
  User = 0,
  AI = 1,
  System = 2,
}

export interface Message {
  role: Role;
  content: string;
}

export interface MessagePair {
  pair_index: number;
  user_msg: Message;
  ai_msg: Message;
}

export interface SessionMeta {
  session_id: string;
  title: string;
  model: string;
  timestamp: number;
}

export interface Session {
  meta_data: SessionMeta;
  pairs: MessagePair[];
}

export interface SearchHit {
  session_id: string;
  matched_pair_indices: number[];
}

export interface SearchResponse {
  hits: SearchHit[];
  sessions: Session[];
  took_ms: number;
}

export interface InitResponse {
  sessions: Session[];
}

const now = Date.now();

// Mock Initial Data (Combined Meta and Data)
export const mockSessions: Session[] = [
  {
    meta_data: {
      session_id: "1001",
      title: "关于 io_uring 性能优化的讨论",
      model: "GPT-4",
      timestamp: now - 86400000 * 2,
    },
    pairs: [
      {
        pair_index: 0,
        user_msg: { role: Role.User, content: "我想在我的 KV 存储引擎中引入 io_uring，有什么最佳实践吗？" },
        ai_msg: { role: Role.AI, content: "引入 io_uring 是个很好的选择，特别是在高并发场景下。几个最佳实践包括：\n1. **SQPOLL 模式**：如果 CPU 资源充足，开启 SQPOLL 可以避免频繁的系统调用。\n2. **Fixed Files**：预先注册文件描述符（IORING_REGISTER_FILES），减少内核在每次提交时的文件查找开销。\n3. **Fixed Buffers**：对于频繁的读写，使用预注册的内存缓冲区（IORING_REGISTER_BUFFERS）。\n4. **Batching**：尽量批量提交 SQE，而不是每次生成一个就提交。" }
      },
      {
        pair_index: 1,
        user_msg: { role: Role.User, content: "如果我采用 Shared Nothing 架构，每个线程一个 io_uring 实例，这样合理吗？" },
        ai_msg: { role: Role.AI, content: "非常合理！这正是 ScyllaDB 和 DragonflyDB 等高性能系统的做法。Thread-per-core 架构配合每个线程独立的 io_uring 实例，可以完全消除线程间的锁竞争。你只需要通过无锁队列或 eventfd 来处理跨线程的通信即可。" }
      }
    ]
  },
  {
    meta_data: {
      session_id: "1002",
      title: "实现 Redis RESP 协议解析",
      model: "Gemini 1.5 Pro",
      timestamp: now - 86400000,
    },
    pairs: [
      {
        pair_index: 0,
        user_msg: { role: Role.User, content: "请帮我写一个 C++ 的 RESP3 协议解析器框架。" },
        ai_msg: { role: Role.AI, content: "解析 RESP 协议通常可以使用状态机来实现。考虑到性能，你可以使用 `std::string_view` 来避免不必要的内存拷贝。以下是一个简单的解析器框架示例..." }
      }
    ]
  },
  {
    meta_data: {
      session_id: "1003",
      title: "FlatBuffers vs Protobuf",
      model: "Claude 3 Opus",
      timestamp: now - 3600000,
    },
    pairs: [
      {
        pair_index: 0,
        user_msg: { role: Role.User, content: "在前后端通信中，FlatBuffers 相比 Protobuf 有什么优势？" },
        ai_msg: { role: Role.AI, content: "FlatBuffers 的最大优势是**无需解析（Zero-parsing）**。当你接收到 FlatBuffers 的二进制数据时，你可以直接通过偏移量访问数据字段，而不需要像 Protobuf 那样先将其反序列化为内存对象。这在处理大量数据或对延迟极其敏感的场景中非常有用。" }
      }
    ]
  }
];

// Mock API Calls
export const api = {
  // Simulate POST /api/init
  init: async (): Promise<InitResponse> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({ sessions: mockSessions });
      }, 300);
    });
  },

  // Simulate POST /api/search
  search: async (keyword: string): Promise<SearchResponse> => {
    return new Promise((resolve) => {
      setTimeout(() => {
        const query = keyword.toLowerCase();
        const hits: SearchHit[] = [];
        const matchedSessions: Session[] = [];

        mockSessions.forEach(session => {
          const matchedPairs: number[] = [];
          session.pairs.forEach(pair => {
            if (pair.user_msg.content.toLowerCase().includes(query) || pair.ai_msg.content.toLowerCase().includes(query)) {
              matchedPairs.push(pair.pair_index);
            }
          });

          if (matchedPairs.length > 0) {
            hits.push({
              session_id: session.meta_data.session_id,
              matched_pair_indices: matchedPairs
            });
            matchedSessions.push(session);
          }
        });

        resolve({
          hits,
          sessions: matchedSessions,
          took_ms: Math.floor(Math.random() * 15) + 2 // 2-16ms
        });
      }, 400);
    });
  }
};
