# HttpServer
http_enable no
httpServer_port 8080

# KVServer
ip 0.0.0.0
port 5005
worker_threads 4

# AOF
aof_enabled no
aof_sync everysec

# RDB
rdb_enabled no
rdb_interval 60

# Master-Slave
cluster_enabled no
is_master yes
master_ip 192.168.183.130
master_port 5005